# Generated by Django 5.1.6 on 2025-02-23 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.checkout'),
        ),
    ]
