# Generated by Django 5.1.6 on 2025-02-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_cartitem_checkout_cartitem_status_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
