# Generated by Django 5.1.6 on 2025-03-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main_app.order'),
        ),
    ]
