# Generated by Django 5.1.6 on 2025-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('clothes', 'Одежда'), ('house_and_garden', 'Дом и сад'), ('beauty', 'Красота'), ('sport', 'Спорт'), ('toys', 'Игрушки'), ('books', 'Книги'), ('auto', 'Авто'), ('food', 'Продукты питания'), ('all', 'Все категории')], default='all', max_length=100),
        ),
    ]
