# Generated by Django 5.1.3 on 2025-05-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.IntegerField(default=0),
        ),
    ]
